// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.prefabsoft.domain;

import java.lang.String;

privileged aspect FakeDomainEntity_Roo_JavaBean {
    
    public String FakeDomainEntity.getName() {
        return this.name;
    }
    
    public void FakeDomainEntity.setName(String name) {
        this.name = name;
    }
    
}
